{% set name = "requests_pkcs12" %}
{% set version = "1.21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 20251453ff795ff687a304f33a7e2ad2f1b29cdf16c9fadc82022ede61788652

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=2.7
    - pip
  run:
    - python >=2.7
    - cryptography >=3.4.7
    - pyopenssl >=20.0.1
    - requests >=2.26.0

test:
  imports:
    - requests_pkcs12

about:
  home: https://github.com/m-click/requests_pkcs12
  license: ISC
  license_file: LICENSE
  summary: This library adds PKCS#12 support to the Python requests library.

  description: |
    Add PKCS#12 support to the requests library in a clean way, without monkey
    patching or temporary files
  dev_url: https://github.com/m-click/requests_pkcs12

extra:
  recipe-maintainers:
    - sodre
