{% set name = "requests_pkcs12" %}
{% set version = "1.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3b3926cf91769d00c7d68ccfc120f03e5ddf5ef48bd9c4b1985dfb40853f8ac5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=2.7
    - pip
  run:
    - python >=2.7
    - cryptography >=3.4.7
    - pyopenssl >=20.0.1
    - requests >=2.26.0

test:
  imports:
    - requests_pkcs12

about:
  home: https://github.com/m-click/requests_pkcs12
  license: ISC
  license_file: LICENSE
  summary: This library adds PKCS#12 support to the Python requests library.

  description: |
    Add PKCS#12 support to the requests library in a clean way, without monkey
    patching or temporary files
  dev_url: https://github.com/m-click/requests_pkcs12

extra:
  recipe-maintainers:
    - agm-eratosth
    - sodre
