{% set name = "requests_pkcs12" %}
{% set version = "1.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: adb9ddafefc4b8aacc037222f199803e4149c22491fdaabf6a9b4fc955a1522a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=2.7
    - pip
  run:
    - python >=2.7
    - pyopenssl >=0.14
    - requests >=2.18.4

test:
  imports:
    - requests_pkcs12

about:
  home: https://github.com/m-click/requests_pkcs12
  license: ISC
  license_file: LICENSE
  summary: This library adds PKCS#12 support to the Python requests library.

  description: |
    Add PKCS#12 support to the requests library in a clean way, without monkey
    patching or temporary files
  dev_url: https://github.com/m-click/requests_pkcs12

extra:
  recipe-maintainers:
    - sodre
