appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: rR8ppuy03GsqDjjLqK8YMdm9Swo3aDm4t9Arhz8Ob1ntIM9n9lZMZvmtSinIMqB5BZLHO1Qf25GxAD8BfNek9DAiPVqkYQDquA+yM/d9Z771wSsHY7RAjxYUYxgYzGudurDuRwhzBJf56HNe/+K/m9lDctC9bO/tDZsUUZBz8XRF4LDuePn5dtTnpOOt6FUIzpKtuuhXFEdKbPHpSBzcr7RKdWQUc9lZC4dxFltS/vjHNrX+4fMeQwqlqJHJ4+1zy6CZ18a7co6ftLVgv5/z6LeyljHKWOb7az5nzgAq0wstzYPL8vNBO66KG39TiOtXvwh6a4PFZDKsyOJRhp3CAZlojgvwjuD629ZpeYkYTnUQeZTWOVPbxzVgV3f+dv9ycgRg/sRxdfmcFymCb2u6TNGhB8H/5qFArgLp9CwZ0hDjvjUDu2WfdlEI9fmAjKxKP4pDk35l+QSzLFAThIhYQXCTo5/O4QiT6523lprGo0FQtjDCyLrZTrfYDlE5e+Ovvxe7vBHXK7/wXtxYEwlR4KlVmdMPBcYG/XuFhdFE71JUL7dMqPFaxUBTS+63WnBY9qTu0quqBr7+3wGZR9czt9bQF5rQ55BiLoOpmijZQYFTIlFRIMWdG5VeUIIJQhjlUT60Dbn+DEmgaPr4NoDi8o/GPEuNEjZxdYAqfjsxeA8=}
conda_forge_output_validation: false
